chore(async): address missing await in `pa.Site._download_backwards()`
Initial evaluation of mypy, yielded this error:
```
juriscraper/opinions/united_states/state/pa.py:265: error: Value of type "Coroutine[Any, Any, None]" must be used  [unused-coroutine]
juriscraper/opinions/united_states/state/pa.py:265: note: Are you missing an await?
```

In 0a121163 (#1843), `_process_html()` was made `async`. Of its two
callers, one switched to `await` and the other was left untouched.
This is all but certain to have been an accident.

It would not be surprising if this is the cause of an unrecognized
bug in the `pa` scraper - where `cases` appears empty because of a
data race invited by the absent await.