chore: address missing `return-value` error in `ClusterSite`
```
juriscraper/ClusterSite.py:279: error: Return value expected  [return-value]
juriscraper/ClusterSite.py:317: error: Return value expected  [return-value]
```