chore(type-annotations): address `arg-type` errors in network_utils
Use assignment expression so that type can be effectively narrowed
for the type checker. This change addresses the following errors:

```
juriscraper/lib/network_utils.py:98: error: Argument 1 to "int" has incompatible type "Any | None"; expected "str | Buffer | SupportsInt | SupportsIndex | SupportsTrunc"  [arg-type]
juriscraper/lib/network_utils.py:133: error: Argument 1 to "int" has incompatible type "Any | None"; expected "str | Buffer | SupportsInt | SupportsIndex | SupportsTrunc"  [arg-type]
```