fix(alaska): correct override of `cleanup_content`
Analysis of the large `AbstractSite` heirarchy for mistaken overrides
revealed this error:

```
juriscraper/opinions/united_states/state/alaska.py:232: error: Signature of "cleanup_content" incompatible with supertype "juriscraper.AbstractSite.AbstractSite"  [override]
juriscraper/opinions/united_states/state/alaska.py:232: note:      Superclass:
juriscraper/opinions/united_states/state/alaska.py:232: note:          @staticmethod
juriscraper/opinions/united_states/state/alaska.py:232: note:          def cleanup_content(content: Any) -> Any
juriscraper/opinions/united_states/state/alaska.py:232: note:      Subclass:
juriscraper/opinions/united_states/state/alaska.py:232: note:          def cleanup_content(self, content: bytes) -> str
```

While this mismatch does not produce an error in practical usage
(surprisingly, the arguments work themselves out), the
implementation that `alaska` uses is out of step with all other
implementations of the method. This introduces unhelpful
confusion that amounts to a bug.

In order to use `@staticmethod`, there are two instances of `self`
that needed to be addressed. `volatile_token_regex` is referred
to using the class `Site` (harmless) and `court_id` is replaced
with literal (precedent for this in `masssuperct`).