chore: address conflicting implementations for `_get_pacer_doc_id`
Static analysis yield the following `no-redef` error:
```
juriscraper/pacer/appellate_docket.py:779: error: Name "_get_pacer_doc_id" already defined on line 652  [no-redef]
```

The static function, `AppellateDocketReport._get_pacer_doc_id()`, is defined twice! The
two implementations are as follows:

```
@staticmethod
def _get_pacer_doc_id(row: html.HtmlElement) -> str:
    return row.xpath(".//a/@data-pacer-doc-id")
```

```
@staticmethod
def _get_pacer_doc_id(cell):
    urls = cell.xpath(".//a")
    if not urls:
        # Entry exists but lacks a URL. Probably a minute order or similar.
        return None
    else:
        doc1_url = urls[0].xpath("./@href")[0]
        return get_pacer_doc_id_from_doc1_url(doc1_url)
```

The nature of Python is such that the later defined function will win.
In this case, that is the 2018 vintage (from 64fb8a0d8). Troublingly,
but not unexpectedly, these functions have different behaviors. The
2023 vintage uses the `data-pacer-doc-id` HTML attribute, while the
2018 vintage extracts the result from the `href` attributed.

I can not judge which is best, but I do known which one has been used
in production for the last three years, and that is the 2018 vintange.
This change ratifies this behavior.

A later change, adopting the more modern `data-pacer-doc-id` attribute
may be a good idea.