chore(lib): strictly check `lib.exceptions`, `lib.log_tools`
Make the few minor changes necessary for the `exceptions` and
`log_tools` modules to pass strict type checking. This done, add
these modules to `mypy.ini` so that CI can enforce correctness.

```
juriscraper/lib/log_tools.py:12: error: Function is missing a type annotation  [no-untyped-def]
juriscraper/lib/log_tools.py:16: error: Function is missing a type annotation  [no-untyped-def]
juriscraper/lib/log_tools.py:33: error: Call to untyped function "errprint" in typed context  [no-untyped-call]
juriscraper/lib/log_tools.py:42: error: Call to untyped function "errprint" in typed context  [no-untyped-call]
juriscraper/lib/log_tools.py:52: error: Call to untyped function "errprint" in typed context  [no-untyped-call]
juriscraper/lib/log_tools.py:56: error: Call to untyped function "errprint" in typed context  [no-untyped-call]
juriscraper/lib/log_tools.py:60: error: Incompatible types in assignment (expression has type "StreamHandler[TextIO | Any]", variable has type "RotatingFileHandler")  [assignment]
juriscraper/lib/exceptions.py:5: error: Call to untyped function "make_default_logger" in typed context  [no-untyped-call]
juriscraper/lib/exceptions.py:29: error: Function is missing a type annotation  [no-untyped-def]
juriscraper/lib/exceptions.py:36: error: Function is missing a type annotation  [no-untyped-def]
juriscraper/lib/exceptions.py:43: error: Function is missing a type annotation  [no-untyped-def]
juriscraper/lib/exceptions.py:50: error: Function is missing a type annotation  [no-untyped-def]
juriscraper/lib/exceptions.py:84: error: Missing type parameters for generic type "dict"  [type-arg]
juriscraper/lib/exceptions.py:100: error: Argument 3 to "log" of "Logger" has incompatible type "**dict[str, dict[str, list[str]]]"; expected "bool | tuple[type[BaseException], BaseException, TracebackType | None] | tuple[None, None, None] | BaseException | None"  [arg-type]
juriscraper/lib/exceptions.py:100: error: Argument 3 to "log" of "Logger" has incompatible type "**dict[str, dict[str, list[str]]]"; expected "bool"  [arg-type]
juriscraper/lib/exceptions.py:100: error: Argument 3 to "log" of "Logger" has incompatible type "**dict[str, dict[str, list[str]]]"; expected "int"  [arg-type]
```