chore(type-annotations): address outstanding `return` errors
A mypy analysis yielded the following `return` errors:

```
juriscraper/pacer/appellate_attachment_page.py:208: error: Missing return statement  [return]
juriscraper/pacer/appellate_attachment_page.py:218: error: Missing return statement  [return]
juriscraper/pacer/appellate_docket.py:630: error: Missing return statement  [return]
juriscraper/opinions/united_states/territories/guam.py:151: error: Missing return statement  [return]
juriscraper/opinions/united_states/state/sc.py:88: error: Missing return statement  [return]
juriscraper/opinions/united_states/state/nh_p.py:197: error: Missing return statement  [return]
```

A review of each implementation and its callers shows that there is
nothing that requires substantive change. The issue is resolved by
adding explicit returns and updating annotated return type to reflect
the actual return type. There is no change in behavior.